### ISSUE TITLE
需要新手教程

### ISSUE THREAD

**Issue by TheOnly8Z** [ExerciseBook/cqsdk-pas#2]
wiki里面几乎没有任何可以给入门用户任何指导的帮助文档。最好能有一个页面详解如何设置一个Hello World的app。

**Comment by ExerciseBook** [comment]
直接编译就是最基础的功能文件。
wiki上面我只写了一些奇怪♂的函数的说明。
我不想写了。。
Wiki你也可以自己编辑一下
