### ISSUE TITLE
CQ_i_sendGroupMsg 发送群消息只有一部分会发送成功

### ISSUE THREAD

**Issue by sgkoishi** [ExerciseBook/cqsdk-pas#4]
在code_eventGroupUpload里面添加几个发送群消息时，只有在CQ_Tools_TextToFile前调用的能成功发送...
否则都只能像截图2中的那样不显示出来...
![cq1](https://user-images.githubusercontent.com/9637711/29483617-d525a308-84dc-11e7-8c82-1afffb4ecc69.png)
![cq2](https://user-images.githubusercontent.com/9637711/29483616-d522df06-84dc-11e7-97c0-247e58eef4b9.png)
![cq3](https://user-images.githubusercontent.com/9637711/29483618-d529fe76-84dc-11e7-822f-67efe313a98d.png)

**Comment by ExerciseBook** [comment]
log一切正常的话那就是被腾讯屏蔽了，自己想办法吧。

**Comment by ExerciseBook** [comment]
不对，我貌似看错了。回头查一下

**Comment by ExerciseBook** [comment]
@zfgong

**Comment by ExerciseBook** [comment]
搞定【其实是不知道为啥突然间又好了。顺便我把我的测试代码上传了上来


相关内容 https://cqp.im/t/34693
